/**
 * Spike 007: in-process gbrain importFromContent write path
 *
 * Validates Phase 7's write path against the v2.0 in-process gbrain architecture
 * (proven for retrieval in spike 006). Calls importFromContent() with a QBO-shape
 * markdown payload against the live Supabase brain under a throwaway sourceId,
 * then runs hybridSearch to prove the round-trip works in-process.
 *
 * The spike does NOT modify types/gbrain.ts. It replicates the same
 * dynamic-import-with-webpackIgnore pattern the shim uses, so a successful
 * spike implies the shim can be safely extended with the same pattern in
 * Phase 7 plan execution.
 *
 * Cleanup: writes are scoped to sourceId='qbo-spike-007'. The script attempts
 * to delete the source partition at end via engine.deleteSource(). If that
 * fails, run `cleanup.ts` separately.
 *
 * How to run:
 *   set -a && . ./.env.local && set +a
 *   bun .planning/spikes/007-gbrain-import-from-content/spike.ts
 *
 * Required env: SUPABASE_DB_URL_POOLER (or GBRAIN_DATABASE_URL), OPENAI_API_KEY
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

// Match the same dynamic-import pattern as types/gbrain.ts so the spike
// validates exactly the runtime path the production shim uses.
async function loadGbrain(subpath: string): Promise<any> {
  return import(/* @vite-ignore */ "gbrain/" + subpath);
}

interface SpikeEvent {
  t: string; // ISO timestamp
  ms: number; // ms since start
  category: "setup" | "config" | "engine" | "ingest" | "search" | "cleanup" | "error";
  message: string;
  data?: unknown;
}

const events: SpikeEvent[] = [];
const t0 = Date.now();

function log(category: SpikeEvent["category"], message: string, data?: unknown) {
  const ms = Date.now() - t0;
  const evt: SpikeEvent = { t: new Date().toISOString(), ms, category, message, ...(data !== undefined ? { data } : {}) };
  events.push(evt);
  const tag = `[${String(ms).padStart(6, " ")}ms] ${category.toUpperCase()}`;
  console.log(`${tag} ${message}${data !== undefined ? "  " + JSON.stringify(data) : ""}`);
}

const SOURCE_ID = "qbo-spike-007";
const SLUG = "originals/qbo-bill-spike-007";
const NOW_ISO = new Date().toISOString().slice(0, 10);

const QBO_PAYLOAD = `---
type: bill
vendor: spike-vendor-007
vendor_slug: spike-vendor-007
date: ${NOW_ISO}
amount: 1234.56
currency: USD
qbo_id: SPIKE-007-bill-1
source: qbo
tags: [spike-007, ingest-test]
---

Bill from [[companies/spike-vendor-007]] for $1234.56 on ${NOW_ISO}.

This is a synthetic QBO-shape bill payload generated by spike 007 to validate
the in-process gbrain importFromContent write path. If you can read this back
via hybridSearch, the spike succeeded.

Description: Whole-bean espresso roast, 12kg, delivered weekly.
`;

async function main() {
  log("setup", "Spike 007 starting", { sourceId: SOURCE_ID, slug: SLUG });

  // ── Env preflight ─────────────────────────────────────────────────────────
  const dbUrl = process.env.GBRAIN_DATABASE_URL ?? process.env.SUPABASE_DB_URL_POOLER;
  const openaiKey = process.env.OPENAI_API_KEY;
  if (!dbUrl) {
    log("error", "No SUPABASE_DB_URL_POOLER or GBRAIN_DATABASE_URL in env");
    process.exit(1);
  }
  if (!openaiKey) {
    log("error", "No OPENAI_API_KEY in env (importFromContent calls embedBatch)");
    process.exit(1);
  }
  log("setup", "Env OK", { dbUrlHost: new URL(dbUrl.replace(/^postgresql:/, "https:")).host, openaiKeyPrefix: openaiKey.slice(0, 6) + "..." });

  // ── Gateway config ────────────────────────────────────────────────────────
  log("config", "Loading gbrain/ai/gateway");
  const gateway = await loadGbrain("ai/gateway");
  log("config", "configureGateway() with process.env snapshot");
  await gateway.configureGateway({ env: { ...process.env } });

  // ── Engine ─────────────────────────────────────────────────────────────────
  log("engine", "Loading gbrain/engine-factory");
  const ef = await loadGbrain("engine-factory");
  const cfg = { engine: "postgres" as const, database_url: dbUrl };
  log("engine", "createEngine(postgres)");
  const engine = await ef.createEngine(cfg);
  log("engine", "engine.connect()");
  await engine.connect(cfg);
  const stats = await engine.getStats();
  log("engine", "Connected — current brain stats", stats);

  // ── Source registration (FINDING: importFromContent requires source row) ─
  log("ingest", `Pre-registering source row id=${SOURCE_ID} (FK pages_source_id_fkey requires it)`);
  await engine.executeRaw(
    `INSERT INTO sources (id, name, config) VALUES ($1, $2, $3::jsonb) ON CONFLICT (id) DO NOTHING`,
    [SOURCE_ID, SOURCE_ID, JSON.stringify({ federated: false, kind: "qbo-spike" })],
  );

  // ── Ingest ─────────────────────────────────────────────────────────────────
  log("ingest", "Loading gbrain/import-file");
  const im = await loadGbrain("import-file");
  log("ingest", `importFromContent(slug=${SLUG}, sourceId=${SOURCE_ID}, forceRechunk=true)`);
  log("ingest", "(this will call OpenAI text-embedding-3-large for chunks)");

  const ingestStart = Date.now();
  let ingestResult: any;
  try {
    ingestResult = await im.importFromContent(engine, SLUG, QBO_PAYLOAD, {
      sourceId: SOURCE_ID,
      forceRechunk: true,
    });
  } catch (err: any) {
    log("error", "importFromContent threw", { name: err?.name, message: err?.message, stack: err?.stack?.split("\n").slice(0, 4) });
    throw err;
  }
  const ingestMs = Date.now() - ingestStart;
  log("ingest", `importFromContent returned in ${ingestMs}ms`, ingestResult);

  // ── Confirm the page is in the DB ──────────────────────────────────────────
  log("ingest", "engine.getPage() to verify persistence");
  const page = await engine.getPage(SLUG, { sourceId: SOURCE_ID });
  log("ingest", "getPage result", page ? {
    slug: page.slug,
    type: page.type,
    title: page.title,
    source_id: page.source_id,
    content_hash: page.content_hash?.slice(0, 12) + "...",
    frontmatter_keys: Object.keys(page.frontmatter ?? {}),
  } : null);

  // ── Idempotency probe — re-import same content ────────────────────────────
  log("ingest", "Re-import same content (idempotency probe)");
  const reIngestStart = Date.now();
  const reIngestResult = await im.importFromContent(engine, SLUG, QBO_PAYLOAD, {
    sourceId: SOURCE_ID,
    forceRechunk: false,
  });
  const reIngestMs = Date.now() - reIngestStart;
  log("ingest", `Re-import returned in ${reIngestMs}ms`, reIngestResult);
  log("ingest", `Expected: status=skipped (content_hash short-circuit). Actual: status=${reIngestResult?.status}`);

  // ── Retrieve via hybridSearch ─────────────────────────────────────────────
  log("search", "Loading gbrain/search/hybrid");
  const hs = await loadGbrain("search/hybrid");
  const query = "espresso bill from spike vendor";
  log("search", `hybridSearch(query="${query}", sourceId=${SOURCE_ID})`);
  const searchStart = Date.now();
  const results = await hs.hybridSearch(engine, query, { sourceId: SOURCE_ID, limit: 5 });
  const searchMs = Date.now() - searchStart;
  log("search", `hybridSearch returned ${results.length} results in ${searchMs}ms`);
  for (const r of results.slice(0, 3)) {
    log("search", `  ${r.score?.toFixed(3)} ${r.slug} — ${r.chunk_text?.slice(0, 80)}...`);
  }

  const targetHit = results.find((r: any) => r.slug === SLUG);
  log("search", targetHit ? "✓ Spike target slug retrieved" : "✗ Spike target slug NOT in top results");

  // ── Tenant-isolation negative probe ───────────────────────────────────────
  log("search", "Negative probe: same query under sourceId='default' (should NOT see qbo-spike-007 page)");
  const negResults = await hs.hybridSearch(engine, query, { sourceId: "default", limit: 5 });
  const negHit = negResults.find((r: any) => r.slug === SLUG);
  log("search", negHit
    ? `✗ ISOLATION FAILURE: spike-007 page leaked into default sourceId (found slug=${negHit.slug})`
    : `✓ Isolation OK: spike-007 page absent from default sourceId (${negResults.length} other results)`);

  // ── Cleanup ───────────────────────────────────────────────────────────────
  log("cleanup", `DELETE FROM sources WHERE id=${SOURCE_ID} (cascades to pages + chunks via FK)`);
  try {
    await engine.executeRaw(`DELETE FROM sources WHERE id = $1`, [SOURCE_ID]);
    log("cleanup", "Source row deleted; cascade swept pages + chunks");
  } catch (err: any) {
    log("cleanup", "Cleanup DELETE failed (non-fatal — orphan row left in sources)", { message: err?.message });
  }

  log("cleanup", "engine.disconnect()");
  await engine.disconnect();
  log("setup", "Spike 007 complete");

  // Write event log to JSON for the README visualization
  const outPath = join(__dirname, "spike-events.json");
  writeFileSync(outPath, JSON.stringify({
    spike: "007",
    finishedAt: new Date().toISOString(),
    totalMs: Date.now() - t0,
    verdicts: {
      ingestSucceeded: !!page,
      idempotencyHonored: reIngestResult?.status === "skipped",
      retrievalSucceeded: !!targetHit,
      isolationOK: !negHit,
    },
    events,
  }, null, 2));
  log("setup", `Event log written to ${outPath}`);

  // Final verdict line for the README to grep
  const ok = !!page && reIngestResult?.status === "skipped" && !!targetHit && !negHit;
  console.log(`\nFINAL VERDICT: ${ok ? "VALIDATED ✓" : "FAILED ✗"}`);
  console.log(`  ingest:       ${page ? "✓" : "✗"}`);
  console.log(`  idempotency:  ${reIngestResult?.status === "skipped" ? "✓" : "✗ (status=" + reIngestResult?.status + ")"}`);
  console.log(`  retrieval:    ${targetHit ? "✓" : "✗"}`);
  console.log(`  isolation:    ${!negHit ? "✓" : "✗"}`);
  process.exit(ok ? 0 : 1);
}

main().catch((err) => {
  log("error", "FATAL", { name: err?.name, message: err?.message });
  console.error(err);
  process.exit(1);
});
