#!/usr/bin/env bun
/**
 * scripts/setup-auth-tables.ts — Idempotent DDL for the auth tables.
 *
 * Creates the `app` schema and auth tables (`app.users`, `app.sessions`,
 * `app.magic_links`) in Supabase Postgres if they do not already exist.
 * Then verifies the app's connection can read its own rows (INSERT-then-SELECT
 * from a fresh connection).
 *
 * The `app` schema is the primary hedge against gbrain's auto-RLS event
 * trigger, which targets public tables (RESEARCH Pitfall 4 / A4). Creating
 * auth tables outside the `public` schema avoids the trigger. The visibility
 * check catches the "silent zero rows" failure if the trigger still fires.
 *
 * Security:
 *   - T-06-03: session id is randomUUID() (122-bit) — unguessable, prevents session fixation.
 *   - T-06-04: Separate `app` schema + visibility check — RLS trigger failure cannot
 *     pass silently.
 *   - T-06-02: Sanitized fatal handler strips postgres:// URLs before any log.
 *
 * Usage:
 *   # Load env vars first (SUPABASE_DB_URL_POOLER or GBRAIN_DATABASE_URL)
 *   set -a && . ./.env.local && set +a
 *   bun scripts/setup-auth-tables.ts
 *
 * Exit codes:
 *   0 — tables created/exist; visibility check passed; probe row cleaned up.
 *   1 — connection failed, DDL failed, or visibility check failed.
 */

import postgres from "postgres";

// ── URL resolution — exact fallback chain from lib/health/probes.ts ────────────
const database_url =
  process.env.GBRAIN_DATABASE_URL ?? process.env.SUPABASE_DB_URL_POOLER;

if (!database_url) {
  console.error(
    "ERROR: GBRAIN_DATABASE_URL or SUPABASE_DB_URL_POOLER must be set",
  );
  process.exit(1);
}

// ── Connections ────────────────────────────────────────────────────────────────
// Connection 1: DDL + INSERT (main)
// Connection 2: fresh connection for the SELECT visibility check (Pitfall 4)
// Both use prepare:false — mandatory for the Supavisor pooler on port 6543.
// database_url is guaranteed non-undefined — validated above (process.exit(1) on falsy)
const DB_URL: string = database_url;
const sql = postgres(DB_URL, { prepare: false });

async function main(): Promise<void> {
  console.log("[setup-auth-tables] Starting DDL setup...");

  // ── Step 1: Create the app schema ──────────────────────────────────────────
  await sql`CREATE SCHEMA IF NOT EXISTS app`;
  console.log("[setup-auth-tables] Schema app: ready");

  // ── Step 2: Create app.users ───────────────────────────────────────────────
  // Columns:
  //   id                  — uuid, gen_random_uuid() default (T-06-03: unguessable)
  //   email               — text, NOT NULL, UNIQUE (the user's login identity)
  //   brain_id            — text, NOT NULL, UNIQUE (= gbrain source_id, D-01/D-11)
  //   brain_slug          — text, NOT NULL (human-readable slug for the dashboard URL)
  //   qbo_realm_id        — nullable, populated in Phase 7 (D-10)
  //   qbo_tokens_encrypted — nullable, AES-256-GCM encrypted blob, Phase 7 (D-10)
  //   created_at          — timestamptz, immutable
  await sql`
    CREATE TABLE IF NOT EXISTS app.users (
      id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
      email                 text        NOT NULL UNIQUE,
      brain_id              text        NOT NULL UNIQUE,
      brain_slug            text        NOT NULL,
      qbo_realm_id          text,
      qbo_tokens_encrypted  text,
      created_at            timestamptz NOT NULL DEFAULT now()
    )
  `;
  console.log("[setup-auth-tables] Table app.users: ready");

  // ── Step 3: Create app.sessions ────────────────────────────────────────────
  // Columns:
  //   id          — uuid PRIMARY KEY (generated by app via randomUUID, T-06-03)
  //   user_id     — uuid FK → app.users(id) CASCADE DELETE
  //   expires_at  — timestamptz (30-day rolling expiry from session creation)
  //   created_at  — timestamptz, immutable
  await sql`
    CREATE TABLE IF NOT EXISTS app.sessions (
      id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id     uuid        NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
      expires_at  timestamptz NOT NULL,
      created_at  timestamptz NOT NULL DEFAULT now()
    )
  `;
  console.log("[setup-auth-tables] Table app.sessions: ready");

  // ── Step 4: Create app.magic_links ─────────────────────────────────────────
  // Columns:
  //   jti         — text PRIMARY KEY (the JWT id from the magic-link token, D-07)
  //   email       — text NOT NULL (for rate-limit query by email, D-09)
  //   used        — boolean NOT NULL DEFAULT false (single-use enforcement)
  //   used_at     — timestamptz nullable (audit trail, T-06-05)
  //   expires_at  — timestamptz NOT NULL (15-minute TTL from issuance, D-07)
  //   created_at  — timestamptz NOT NULL (rate-limit window anchor, D-09)
  await sql`
    CREATE TABLE IF NOT EXISTS app.magic_links (
      jti         text        PRIMARY KEY,
      email       text        NOT NULL,
      used        boolean     NOT NULL DEFAULT false,
      used_at     timestamptz,
      expires_at  timestamptz NOT NULL,
      created_at  timestamptz NOT NULL DEFAULT now()
    )
  `;
  console.log("[setup-auth-tables] Table app.magic_links: ready");

  // ── Step 5: Create indexes ─────────────────────────────────────────────────
  // idx_sessions_user_id — efficient JOIN / ON DELETE CASCADE + session lookups by user
  await sql`CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON app.sessions (user_id)`;
  console.log("[setup-auth-tables] Index idx_sessions_user_id: ready");

  // idx_magic_links_email — the D-09 rate-limit query filters by email + created_at
  await sql`CREATE INDEX IF NOT EXISTS idx_magic_links_email ON app.magic_links (email)`;
  console.log("[setup-auth-tables] Index idx_magic_links_email: ready");

  // ── Step 6: RLS-visibility check (Pitfall 4 / T-06-04) ─────────────────────
  // INSERT a probe row into app.users, then SELECT it back from a SEPARATE fresh
  // connection. If the SELECT returns zero rows, gbrain's auto-RLS trigger caught
  // app.users despite the separate schema — fail loudly with a remediation hint.
  console.log("[setup-auth-tables] Running RLS-visibility check...");

  // 6a. Insert probe row via the main connection
  const insertResult = await sql<{ id: string }[]>`
    INSERT INTO app.users (email, brain_id, brain_slug)
    VALUES ('__setup_probe__@example.invalid', 'setup-probe', 'setup-probe')
    RETURNING id
  `;
  const probeRow = insertResult[0];
  if (!probeRow) {
    console.error("[setup-auth-tables] FATAL: probe INSERT returned no row");
    process.exit(1);
  }
  const probeId = probeRow.id;
  console.log(`[setup-auth-tables] Probe row inserted: id=${probeId}`);

  // 6b. Open a fresh connection and SELECT the probe row back
  const sqlFresh = postgres(DB_URL, { prepare: false, max: 1 });
  let visibilityPassed = false;
  try {
    const rows = await sqlFresh<{ id: string }[]>`
      SELECT id FROM app.users WHERE id = ${probeId}
    `;
    visibilityPassed = rows.length > 0;
  } finally {
    await sqlFresh.end({ timeout: 5 });
  }

  if (!visibilityPassed) {
    // Clean up probe row before failing so the script is idempotent on re-run
    await sql`DELETE FROM app.users WHERE id = ${probeId}`;
    console.error(
      "[setup-auth-tables] FATAL: RLS-visibility check FAILED — " +
        "the INSERT row is not visible from a fresh connection.\n" +
        "Remediation options:\n" +
        "  1. Add an explicit allow-all RLS policy for the app's connection role:\n" +
        "       ALTER TABLE app.users ENABLE ROW LEVEL SECURITY;\n" +
        "       CREATE POLICY allow_all ON app.users USING (true) WITH CHECK (true);\n" +
        "  2. If the connection uses a trusted service role:\n" +
        "       ALTER TABLE app.users DISABLE ROW LEVEL SECURITY;\n" +
        "  3. Verify gbrain's auto-RLS trigger does not target the `app` schema.",
    );
    process.exit(1);
  }

  // 6c. Clean up probe row
  await sql`DELETE FROM app.users WHERE id = ${probeId}`;
  console.log("[setup-auth-tables] Probe row deleted");

  console.log(
    "[setup-auth-tables] Auth tables ready / row visible — setup complete.",
  );
}

main()
  .catch((err) => {
    // Never echo the DB URL or a raw connection error that might contain it
    const msg = err instanceof Error ? err.message : String(err);
    const safe = msg.replace(/postgres:\/\/[^\s]+/gi, "[redacted]");
    console.error("[setup-auth-tables] FATAL:", safe);
    process.exit(1);
  })
  .finally(() => {
    // Always close the main connection
    sql.end({ timeout: 5 }).catch(() => {});
  });
