/**
 * lib/auth/session.ts — DB-backed session lifecycle (create / validate / destroy).
 *
 * Uses the sql singleton from lib/auth/store.ts — does NOT construct a second
 * postgres() client. All session IDs are generated by node:crypto.randomUUID()
 * (122-bit cryptographically-random UUIDs, T-06-03: unguessable, prevents session
 * fixation and hijacking).
 *
 * Session model (D-04):
 *   - Opaque random session ID in the cookie (name: qb_session, D-05)
 *   - Session row in app.sessions carries (id, user_id, expires_at)
 *   - Sign-out deletes the row → true server-side revocation (AUTH-07)
 *
 * Security:
 *   T-06-03: randomUUID() — 122-bit, cryptographically random, cannot be guessed
 *   T-06-02: Never log session ids or user_ids (metadata only)
 *
 * Analog: lib/jobs/store.ts (role-match — small CRUD module over the shared sql)
 */

import { randomUUID } from "node:crypto";
import { sql } from "./store";

/**
 * Create a new session for a user.
 *
 * Generates an opaque random session ID (randomUUID, 122-bit), inserts a row
 * into app.sessions with a 30-day expiry, and returns the session ID.
 * The caller sets this ID as the qb_session HttpOnly cookie (D-05).
 *
 * @param userId - The app.users.id for the authenticated user
 * @returns      - The new session ID (an opaque UUID string, not the user ID)
 */
export async function createSession(userId: string): Promise<string> {
  const id = randomUUID(); // 122-bit unguessable (T-06-03)
  await sql`
    INSERT INTO app.sessions (id, user_id, expires_at)
    VALUES (${id}, ${userId}, now() + interval '30 days')
  `;
  return id;
}

/**
 * Validate a session and return the associated user_id.
 *
 * Returns the user_id for a non-expired session, null for an expired or
 * missing session. Does NOT extend the session expiry (rolling window is a
 * Phase 6+ enhancement, deferred per CONTEXT.md).
 *
 * @param id - The session ID from the qb_session cookie
 * @returns  - The user_id (UUID string) if valid, null otherwise
 */
export async function validateSession(id: string): Promise<string | null> {
  const rows = await sql<{ user_id: string }[]>`
    SELECT user_id FROM app.sessions
    WHERE id = ${id}
      AND expires_at > now()
  `;
  return rows[0]?.user_id ?? null;
}

/**
 * Destroy a session (true server-side revocation, AUTH-07).
 *
 * Deletes the app.sessions row. The cookie becomes invalid immediately because
 * subsequent validateSession calls will find no matching row.
 * The caller must also clear the cookie via Set-Cookie maxAge=0 (D-05).
 *
 * @param id - The session ID from the qb_session cookie
 */
export async function destroySession(id: string): Promise<void> {
  await sql`DELETE FROM app.sessions WHERE id = ${id}`;
}
